Migration table
thm-mni-ii/kanban pull request #21
Opened 2024-08-26 16:11 UTC by S-Reinhard

Prevents the SQL setup files from being executed every time the application is started
- Only scripts that have never been run before are now executed during setup.
- Once a script has been successfully executed, it is stored in the database to prevent future execution.

Before testing, you should back up the test data and then run `docker-compose down -v` to reset the database.

2024-09-05 07:48 UTC, Zitrone44 requested changes
Looks good just one thing:

2024-09-05 07:48 UTC, Zitrone44 commented on backend/database/setup/runner/sql-runner.py
>          with connect("host=kandb port=5432 dbname=kandb user=kanuser password=secret") as conn:
Please use environment variables here.

2024-09-27 20:23 UTC, S-Reinhard commented on backend/database/setup/runner/sql-runner.py
>          with connect("host=kandb port=5432 dbname=kandb user=kanuser password=secret") as conn:
Done

2024-10-01 06:51 UTC, Zitrone44 approved these changes

2024-10-01 06:51 UTC, merged